apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-14T15:37:37Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "7709"
  uid: 16bac3e3-cf21-4d54-9b76-29c2674365d9
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.99.45.93
  clusterIPs:
  - 10.99.45.93
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32708
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
